<?php
/**
 * @file
 * Code for the My Content feature.
 */

include_once 'v_my_content.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function v_my_content_form_views_exposed_form_alter(&$form, &$form_state) {
  if (strpos($form['#id'], 'views-exposed-form-my-content-page-') !== FALSE) {
    $form['date_filter']['min']['#title'] = t('From Post Date');
    $form['date_filter']['max']['#title'] = t('To Post Date');
  }
}
