<?php
/**
 * @file
 * Code for the My Content feature.
 */

include_once 'v_my_content.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function v_my_content_form_views_exposed_form_alter(&$form, &$form_state) {
  if (strpos($form['#id'], 'views-exposed-form-my-content-page-') !== FALSE) {
    $form['date_filter']['min']['#title'] = t('From Post Date');
    $form['date_filter']['max']['#title'] = t('To Post Date');

    $field_name = 'field_flea_market_item_type';
    $form_field = $field_name . '_value';

    // Get the options settings from the Select or other configuration and
    // render this filter as a select.
    if (isset($form[$form_field])) {
      $field_info = field_info_instance('node', $field_name, 'flea_market_post');
      $available_options = $field_info['widget']['settings']['available_options'];
      $options = array(
        '' => 'All Categories',
      );

      foreach (explode("\n", $available_options) as $line) {
        $line = trim($line);
        if (!empty($line)) {
          $parts = explode('|', $line);
          if (count($parts) == 2) {
            $options[$parts[0]] = $parts[1];
          }
          else {
            $options[$line] = $line;
          }
        }
      }

      $form[$form_field]['#type'] = 'select';
      $form[$form_field]['#multiple'] = FALSE;
      $form[$form_field]['#size'] = 0;
      $form[$form_field]['#options'] = $options;
    }
  }
}
