<?php
/**
 * @file
 * Code for the SLAC IP Core feature.
 */

include_once 'slac_ip_core.features.inc';
/**
 * @file
 * Code for the SLAC IP core feature.
 */

/**
 * Implements hook_entity_info().
 */
function slac_ip_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['headline'] = array(
    'label' => t('Headline'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_date_formats().
 */
function slac_ip_core_date_formats() {
  return array(
    array(
      'type' => 'slac_ip_access_date',
      'format' => 'g:i a, l, M j, Y',
      'locales' => array(),
    ),
    array(
      'type' => 'slac_ip_published_date',
      'format' => 'F j, Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function slac_ip_core_date_format_types() {
  return array(
    'slac_ip_access_date' => t('SLAC Access Info.: g:i a, l, M j, Y'),
    'slac_ip_published_date' => t('SLAC published date: F j, Y'),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function slac_ip_core_field_formatter_info() {
  return array(
    'slac_event_date_formatter' => array(
      'label' => t('SLAC Custom Event Date Format'),
      'field types' => array('datetime'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function slac_ip_core_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'slac_event_date_formatter':
      foreach ($items as $delta => $item) {
        $value1 = new DateTime($item['value']);
        $value2 = new DateTime($item['value2']);
        $interval = $value1->diff($value2);

        if ($interval->days == 0) {
          // Single day event.
          if (empty($item['value2']) || $item['value'] == $item['value2']) {
            $markup = t(
                '!date (All Day)',
                array(
                  '!date' => $value1->format('l, F d, Y'),
                ));
          }
          else {
            $markup = t(
                '!start-date-!end-date',
                array(
                  '!start-date' => $value1->format('l, F d, Y, g a'),
                  '!end-date' => $value2->format('g a'),
                ));
          }
        }
        else {
          // Multi-day event.
          $markup = t(
              '!start-date - !end-date',
              array(
                '!start-date' => $value1->format('l, M. d, Y, g a'),
                '!end-date' => $value2->format('l, M. d, Y, g a'),
              ));
        }

        $element[$delta] = array('#markup' => $markup);
      }
      break;
  }

  return $element;
}
