<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'ct_news.features.inc';

/**
 * Implements hook_form_FORMID_alter().
 */
function ct_news_form_news_node_form_alter(&$form, &$form_state) {
  // field_shared_promote_news will always be turned on for News nodes,
  // this is to support views like News Archive which list News, Event, Access
  // nodes and need to filter out items that do not have 'Promote...' set to On.
  $form['field_shared_promote_news']['#value'] = 1;
  $form['field_shared_promote_news']['#access'] = FALSE;

  // Add a help-like message to link users to the Event creation if they wanted
  // that instead.
  $event_help = array(
    '#type' => 'markup',
    '#markup' => '<span class="event_help">' .
      t("Did you want to !create_event_link instead? An Event can still appear in the news list, but also has a start and end date, a location, and appears on the SLAC Today calendar.",
          array(
            '!create_event_link' => l(t('create an event'), 'node/add/event/slac'),
          )
        ) . '</span>',
  );
  array_unshift($form, $event_help);
}
