<?php

/**
 * @file
 * Provides custom panes.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_ip_panes_ctools_plugin_directory($owner, $plugin) {
  if ($owner == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_theme().
 */
function slac_ip_panes_theme($existing, $type, $theme, $path) {
  $theme_path = drupal_get_path('module', 'slac_ip_panes') . '/theme';
  $theme_file = 'slac_ip_upcoming_events.theme.inc';
  return array(
    'slac_ip_upcoming_events' => array(
      'variables' => array(
        'content' => NULL,
      ),
      'path' => $theme_path,
      'template' => 'slac_ip_upcoming_events',
    ),
    'slac_ip_upcoming_events_event' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'path' => $theme_path,
      'template' => 'slac_ip_upcoming_events_event',
      'file' => $theme_file,
    ),
//    'slac_ip_upcoming_events_day' => array(
//      'variables' => array(
//        'month' => NULL,
//        'day' => NULL,
//        'rendered_events' => NULL,
//      ),
//      'path' => $theme_path,
//      'file' => $theme_file,
//    ),
  );
}
