<?php
/**
 * @file
 * Code for the Event feature.
 */

include_once 'v_search.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function v_search_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-search-page' && $_GET['q'] == 'search') {

    // We need to limit the exposed content types filters to specific types but
    // this means that all of the options will be selected by default. We are
    // overriding it here.
    $form['secondary']['type']['#default_value'] = false;
    $form['secondary']['second_submit'] = array(
      '#name' => '',
      '#type' => 'submit',
      '#value' => 'Search',
      '#id' => 'edit-second-submit-search',
      '#access' => TRUE,
    );

    // Wrap the full text search and submit in container div.
    $form['search']['search_container'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'search-wrapper',
        ),
      ),
    );

    // Reorder the form values and unset the originals.
    $form['search']['search_container']['search_api_views_fulltext'] = $form['search_api_views_fulltext'];
    unset($form['search_api_views_fulltext']);
    $form['search']['search_container']['submit'] = $form['submit'];
    unset($form['submit']);
    $form['search']['secondary'] = $form['secondary'];
    unset($form['secondary']);
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'v_search') . '/js/highlight-results.js' => array(
        'type' => 'file',
      ),
    );
  }

}
