<?php
/**
 * @file
 * Code for the SLAC IP Content Admin feature.
 */

include_once 'slac_ip_content_admin.features.inc';

/**
 * Implements hook_menu_alter().
 *
 * Alters the webform admin listing menu item so that it will not appear as a
 * local task, but will still be in the Content menu.
 *
 * Alters the tab for 'Content' to reflect that it is for 'All Content'.
 */
function slac_ip_content_admin_menu_alter(&$items) {
  $items['admin/content/webform']['type'] = MENU_NORMAL_ITEM;

  $items['admin/content/node']['title'] = t('All Content');
}

/**
 * Implements hook_form_alter().
 */
function slac_ip_content_admin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if (strpos($form['#id'], 'views-exposed-form-administration-nodes-slac-') === 0) {
      $form['date_filter']['min']['#title'] = t('From Post Date');
      $form['date_filter']['max']['#title'] = t('To Post Date');
    }
  }
}
