<?php

/**
 * @file
 * SLAC Alert functionality.
 */

/**
 * Implements hook_block_info().
 */
function slac_alert_block_info() {
  $blocks = array();
  $blocks['slac_alert'] = array(
    'info' => t('SlAC Alert'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function slac_alert_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'slac_alert':
      $form['slac_alert_active'] = array(
        '#type' => 'checkbox',
        '#title' => t('Active'),
        '#description' => t('When active, the alert block will be shown on every page.'),
        '#default_value' => variable_get('slac_alert_active'),
      );

      $form['slac_alert_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Text'),
        '#default_value' => variable_get('slac_alert_body'),
      );

      $form['slac_alert_link'] = array(
        '#type' => 'textfield',
        '#title' => t('Link'),
        '#description' => t('If link is entered, the entire block will be a link'),
        '#default_value' => variable_get('slac_alert_link'),
      );

      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function slac_alert_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'slac_alert':
      variable_set('slac_alert_active', $edit['slac_alert_active']);
      variable_set('slac_alert_body', $edit['slac_alert_body']['value']);
      variable_set('slac_alert_link', $edit['slac_alert_link']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function slac_alert_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'slac_alert':
      $block['content'] = array(
        '#theme' => 'slac_alert',
        '#active' => variable_get('slac_alert_active'),
        '#body' => variable_get('slac_alert_body'),
        '#link' => variable_get('slac_alert_link'),
      );

      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function slac_alert_theme($existing, $type, $theme, $path) {
  return array(
    'slac_alert' => array(
      'variables' => array(
        'active' => NULL,
        'body' => NULL,
        'link' => NULL,
      ),
      'template' => 'theme/slac-alert',
    ),
  );
}
